In [1]:
from PIL import Image
import numpy as np
import os

# ASCII_CHARS below is arragned in order of thin to thick strokes. This will help map intensity of image to weight of character strokes
ASCII_CHARS = "`^\",:;Il!i~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$"
ASCII_SIZE = len(ASCII_CHARS)
MAX_PIXEL_VALUE = 255
NUM_OF_BANDS = 3




In [7]:
def clear():
    os.system( 'cls' )

def getPixelArray(img,xSize,ySize):
    imageArray = np.asarray(img)
    newPixelArray= []
    for i in range(ySize):
        newValRow = []
        for j in range(xSize):
            newValRow.append(sum(imageArray[i,j])/NUM_OF_BANDS)
        #print(newValRow) #[DEBUG] print out the row with new values for each pixel
        #print("#################")
        newPixelArray.append(newValRow)
    return(newPixelArray)

#mapAsciiArray creates an array with the corresponding ascii indexes based on the calculated brightness value of each pixel    
def mapAsciiArray(pixelArray,xSize,ySize):
    asciiArraySize = len(ASCII_CHARS)
    asciiArray = []
    for i in range(ySize):
        newValRow = []
        for j in range(xSize):
            charMapIndex = (ASCII_SIZE*pixelArray[i][j])/MAX_PIXEL_VALUE
            newValRow.append(ASCII_CHARS[charMapIndex])
            #newValRow.append(charMapIndex)
        #print(newValRow) #[DEBUG] print out the row with new values for each pixel
        asciiArray.append(newValRow)
    return(asciiArray)

def printAsciiImage(asciiArray,xSize,ySize):
    for i in range(ySize):
        for j in range(xSize):
            print(asciiArray[i][j]),
            
#def updateImage():
    
    
    


In [12]:

im1 = Image.open("google.jpeg")
xSize = im1.size[0]
ySize = im1.size[1]
#Print the image
print(im1.format,im1.size,im1.mode)
print(xSize,ySize)

imgData = getPixelArray(im1,xSize,ySize)
asciiArray = mapAsciiArray(imgData,xSize,ySize)
#printAsciiImage(asciiArray,xSize,ySize)
im1.show()

('JPEG', (620, 413), 'RGB')
(620, 413)


In [4]:
print(len(imgData[0]))

960


In [ ]:
print(max(imgData[0]))
print(ASCII_CHARS[0])

In [3]:
print(chr(100))

d


In [17]:
imageArray = np.asarray(im1)
print(imageArray[0])

[[  1 116 209]
 [  1 116 209]
 [  1 116 209]
 ..., 
 [  3 133 217]
 [  3 133 217]
 [  3 133 217]]


In [11]:
print(ASCII_CHARS)

`^",:;Il!i~+_-?][}{1)(|\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$


In [22]:
65*250/255

63

In [25]:
charMapIndex = ASCII_SIZE * (asciipixelArray[0][0]/MAX_PIXEL_VALUE)

NameError: name 'asciipixelArray' is not defined

`
^


In [15]:
print(1), 
print(2)

1 2


In [19]:
print ('1'+'2'),
print('')
print('1'+'2')

12 
12


In [21]:
im1.show()
im2=im1.resize(400,400)

ValueError: unknown resampling filter

In [23]:
a = [1,2,3,4]
print(a)
join()
print("".join(a))

[1, 2, 3, 4]


NameError: name 'join' is not defined

In [25]:
print("".join(asciiArray[0]))

````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
